export const IARE_ACTIONS = {

    REMOVE_ALL_FILTERS: {
        key:"REMOVE_ALL_FILTERS",
    },

    FILTER_BY_REFERENCE_STATS: {
        key:"FILTER_BY_REFERENCE_STATS",
    },

    SHOW_REFERENCE_VIEWER: {
        key:"SHOW_REFERENCE_VIEWER",
    },

    SHOW_REFERENCE_VIEWER_FOR_URL: {
        key:"SHOW_REFERENCE_VIEWER_FOR_URL",
    },

    CHANGE_REF_VIEW_SELECTION: {
        key:"CHANGE_REF_VIEW_SELECTION",
    },

    SET_ACTIONABLE_FILTER: {
        key: "SET_ACTIONABLE_FILTER"
    },
}
